version: '3'
# 2 or 3
services:
  app:
# web or node
    container_name: docker-node-mongo
    restart: always
    build: .
# current directory
    ports:
      - '80:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
# we are not building here that's why we extracted from docker hub
    ports:
      - '27017:27017'
